# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 089db5dbc9fff82b81845b54a8e26f191b40c680dc69159278e827910b4401710d7b1c60b6d146192bab4d391933a2097029632f5d7d16b3ba162633c1d25c4a

test:
  secret_key_base: d26c2ccc825ca5658df4163abf65a3f841e2cd9a718d94a8d9d8af279093fece9cbe550ecc147eee20422c2489c682d6fbf78865cf9793362ee5005bf03d0e01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
